### ISSUE TITLE
Error parsing __init__.py: docstring exists but does not start with triple quotes

### ISSUE THREAD

**Issue by swt2c** [adang1345/delvewheel#23]
First of all, thank you for creating this tool!

I'm running into an issue trying to repair a wheel:

```
(env) C:\Users\Scott Talbert\pycurl>delvewheel repair --add-path "C:\Users\Scott Talbert\vcpkg\installed\x64-windows\bin" dist/pycurl-7.44.1-cp38-cp38-win_amd64.whl
repairing dist/pycurl-7.44.1-cp38-cp38-win_amd64.whl
finding DLL dependencies
copying DLLs into pycurl-7.44.1.data\platlib
mangling DLL names
calculating DLL load order
patching curl\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Scott Talbert\pycurl\env\Scripts\delvewheel.exe\__main__.py", line 7, in <module>
  File "c:\users\scott talbert\pycurl\env\lib\site-packages\delvewheel\__main__.py", line 70, in main
    wr.repair(args.target, no_mangles, args.no_mangle_all, args.lib_sdir)
  File "c:\users\scott talbert\pycurl\env\lib\site-packages\delvewheel\wheel_repair.py", line 504, in repair
    self._patch_init(init_path, libs_dir_name, load_order_filename)
  File "c:\users\scott talbert\pycurl\env\lib\site-packages\delvewheel\wheel_repair.py", line 229, in _patch_init
    raise ValueError('Error parsing __init__.py: docstring exists but does not start with triple quotes')
ValueError: Error parsing __init__.py: docstring exists but does not start with triple quotes
```

Here is the wheel that I'm trying to repair (renamed to zip):
[pycurl-7.44.1-cp38-cp38-win_amd64.zip](https://github.com/adang1345/delvewheel/files/7917468/pycurl-7.44.1-cp38-cp38-win_amd64.zip)

**Comment by swt2c** [comment]
Thanks a lot for the quick fix!
