### ISSUE TITLE
Install on Windows 11 

### ISSUE THREAD

**Issue by galabovaa** [adang1345/delvewheel#40]
Hi, 

I have used delvewheel before and it worked great! Thank you for developing and maintaining this.

Something must have changed, because now when I pip install delvewheel on Windows 11 and try to use it I get the following error: 
```
PS C:\Users\galab\source\repos\ERGO-Code\HiGHS\build\highspy> delvewheel
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\galab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\delvewheel.exe\__main__.py", line 4, in <module>
  File "C:\Users\galab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\delvewheel\__main__.py", line 4, in <module>
    from ._wheel_repair import WheelRepair
  File "C:\Users\galab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\delvewheel\_wheel_repair.py", line 16, in <module>
    from . import _dll_utils
  File "C:\Users\galab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\delvewheel\_dll_utils.py", line 209, in <module>
    _translate_directory = _translate_directory()
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\galab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\delvewheel\_dll_utils.py", line 129, in _translate_directory
    interpreter_arch = get_arch(sys.executable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\galab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\delvewheel\_dll_utils.py", line 76, in get_arch
    with open(path, 'rb') as file:
         ^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\galab\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\python.exe'
```
I tried on a couple different machines and on a virtual machine with Windows 10 and I still get the same error. 

Do you know how I can fix this one? 

Thank you, 
Ivet

**Comment by adang1345** [comment]
This looks like the same issue as https://github.com/pre-commit/pre-commit/issues/1830, which is specific to the Windows Store version of Python. If you use a version of Python installed from https://www.python.org/downloads/windows/ or from https://www.nuget.org/packages/python, then the issue should not occur. Or you could create a virtual environment and try running `delvewheel` in the virtual environment instead.

In the meantime, I will work on a fix for this.

**Comment by galabovaa** [comment]
Thank you so much for the quick response, installing python from python.org did the trick!
