### ISSUE TITLE
Bug with absolute_import

### ISSUE THREAD

**Issue by asfixia** [adang1345/delvewheel#8]
from __future__ import absolute_import

**Comment by asfixia** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\danilo\AppData\Local\Dinamica EGO 5\PyEnvironment\Lib\site-packages\rasterio\__init__.py", line 25
    from __future__ import absolute_import
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file

**Comment by adang1345** [comment]
The bug is that the patch to `__init__.py` is inserted prior to the `from __future__ import`. I will work on a solution to ensure that the patch is placed after the `from __future__ import`.
